using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace IOToolkit
{
    public enum InputEvent
    {
        IE_Pressed = 0,
        IE_Released = 1,
        IE_Repeat = 2,
        IE_DoubleClick = 3,
        IE_Axis = 4,

        /// <summary>
        /// NetIO 帧通道事件 (插件协议 ws/tcp). 由 IOEvent trigger="device:name@channel" 声明,
        /// 在 UNIPlayer 层通过 NetIOExtensions.On / OnRequest 订阅, 脚本中用 reply(data) 回复 req.
        /// </summary>
        IE_Channel = 5,
        IE_MAX = 6
    }

    public class Key
    {
        Key(string InID = "string InID")
        {
            this.ID = InID;
        }

        // ------------- Properties -----------
        string ID;

        public override string ToString()
        {
            return this.ID;
        }

        public static implicit operator Key(string v)
        {
            return new Key(v);
        }

        public static implicit operator string(Key v)
        {
            return v.ID;
        }

        public static bool operator ==(Key lhs, Key rhs)
        {
            if (ReferenceEquals(rhs, null))
                return false;
            if (ReferenceEquals(rhs, lhs))
                return true;
            return lhs.ID == rhs.ID;
        }

        public static bool operator !=(Key lhs, Key rhs)
        {
            return lhs.ID != rhs.ID;
        }

        public override bool Equals(object rhs)
        {
            if (this.GetType() != rhs.GetType())
                return false;
            Key _rhs = rhs as Key;
            return _rhs == this;
        }

        public override int GetHashCode()
        {
            return StringComparer.InvariantCulture.GetHashCode(ID);
        }
    }

    public struct IOKeyCode
    {
        /** Standard Keyboard & Mouse */
        public static readonly Key AnyKey = "AnyKey";
        public static readonly Key MouseX = "MouseX";
        public static readonly Key MouseY = "MouseY";
        public static readonly Key MouseScrollUp = "MouseScrollUp";
        public static readonly Key MouseScrollDown = "MouseScrollDown";
        public static readonly Key MouseWheelAxis = "MouseWheelAxis";

        public static readonly Key LeftMouseButton = "LeftMouseButton";
        public static readonly Key RightMouseButton = "RightMouseButton";
        public static readonly Key MiddleMouseButton = "MiddleMouseButton";
        public static readonly Key ThumbMouseButton = "ThumbMouseButton";
        public static readonly Key ThumbMouseButton2 = "ThumbMouseButton2";

        public static readonly Key BackSpace = "BackSpace";
        public static readonly Key Tab = "Tab";
        public static readonly Key Enter = "Enter";
        public static readonly Key Pause = "Pause";

        public static readonly Key CapsLock = "CapsLock";
        public static readonly Key Escape = "Escape";
        public static readonly Key SpaceBar = "SpaceBar";
        public static readonly Key PageUp = "PageUp";
        public static readonly Key PageDown = "PageDown";
        public static readonly Key End = "End";
        public static readonly Key Home = "Home";

        public static readonly Key Left = "Left";
        public static readonly Key Up = "Up";
        public static readonly Key Right = "Right";
        public static readonly Key Down = "Down";

        public static readonly Key Insert = "Insert";
        public static readonly Key Delete = "Delete";

        public static readonly Key Zero = "Zero";
        public static readonly Key One = "One";
        public static readonly Key Two = "Two";
        public static readonly Key Three = "Three";
        public static readonly Key Four = "Four";
        public static readonly Key Five = "Five";
        public static readonly Key Six = "Six";
        public static readonly Key Seven = "Seven";
        public static readonly Key Eight = "Eight";
        public static readonly Key Nine = "Nine";

        public static readonly Key A = "A";
        public static readonly Key B = "B";
        public static readonly Key C = "C";
        public static readonly Key D = "D";
        public static readonly Key E = "E";
        public static readonly Key F = "F";
        public static readonly Key G = "G";
        public static readonly Key H = "H";
        public static readonly Key I = "I";
        public static readonly Key J = "J";
        public static readonly Key K = "K";
        public static readonly Key L = "L";
        public static readonly Key M = "M";
        public static readonly Key N = "N";
        public static readonly Key O = "O";
        public static readonly Key P = "P";
        public static readonly Key Q = "Q";
        public static readonly Key R = "R";
        public static readonly Key S = "S";
        public static readonly Key T = "T";
        public static readonly Key U = "U";
        public static readonly Key V = "V";
        public static readonly Key W = "W";
        public static readonly Key X = "X";
        public static readonly Key Y = "Y";
        public static readonly Key Z = "Z";

        public static readonly Key NumPadZero = "NumPadZero";
        public static readonly Key NumPadOne = "NumPadOne";
        public static readonly Key NumPadTwo = "NumPadTwo";
        public static readonly Key NumPadThree = "NumPadThree";
        public static readonly Key NumPadFour = "NumPadFour";
        public static readonly Key NumPadFive = "NumPadFive";
        public static readonly Key NumPadSix = "NumPadSix";
        public static readonly Key NumPadSeven = "NumPadSeven";
        public static readonly Key NumPadEight = "NumPadEight";
        public static readonly Key NumPadNine = "NumPadNine";

        public static readonly Key Multiply = "Multiply";
        public static readonly Key Add = "Add";
        public static readonly Key Subtract = "Subtract";
        public static readonly Key Decimal = "Decimal";
        public static readonly Key Divide = "Divide";

        public static readonly Key F1 = "F1";
        public static readonly Key F2 = "F2";
        public static readonly Key F3 = "F3";
        public static readonly Key F4 = "F4";
        public static readonly Key F5 = "F5";
        public static readonly Key F6 = "F6";
        public static readonly Key F7 = "F7";
        public static readonly Key F8 = "F8";
        public static readonly Key F9 = "F9";
        public static readonly Key F10 = "F10";
        public static readonly Key F11 = "F11";
        public static readonly Key F12 = "F12";

        public static readonly Key NumLock = "NumLock";

        public static readonly Key ScrollLock = "ScrollLock";

        public static readonly Key LeftShift = "LeftShift";
        public static readonly Key RightShift = "RightShift";
        public static readonly Key LeftControl = "LeftControl";
        public static readonly Key RightControl = "RightControl";
        public static readonly Key LeftAlt = "LeftAlt";
        public static readonly Key RightAlt = "RightAlt";
        public static readonly Key LeftCommand = "LeftCommand";
        public static readonly Key RightCommand = "RightCommand";
        public static readonly Key Invalid = "Invalid";

        /** Buttons for PCI & JoyStick  */
        public static readonly Key Button_00 = "Button_00";
        public static readonly Key Button_01 = "Button_01";
        public static readonly Key Button_02 = "Button_02";
        public static readonly Key Button_03 = "Button_03";
        public static readonly Key Button_04 = "Button_04";
        public static readonly Key Button_05 = "Button_05";
        public static readonly Key Button_06 = "Button_06";
        public static readonly Key Button_07 = "Button_07";
        public static readonly Key Button_08 = "Button_08";
        public static readonly Key Button_09 = "Button_09";
        public static readonly Key Button_10 = "Button_10";
        public static readonly Key Button_11 = "Button_11";
        public static readonly Key Button_12 = "Button_12";
        public static readonly Key Button_13 = "Button_13";
        public static readonly Key Button_14 = "Button_14";
        public static readonly Key Button_15 = "Button_15";
        public static readonly Key Button_16 = "Button_16";
        public static readonly Key Button_17 = "Button_17";
        public static readonly Key Button_18 = "Button_18";
        public static readonly Key Button_19 = "Button_19";
        public static readonly Key Button_20 = "Button_20";
        public static readonly Key Button_21 = "Button_21";
        public static readonly Key Button_22 = "Button_22";
        public static readonly Key Button_23 = "Button_23";
        public static readonly Key Button_24 = "Button_24";
        public static readonly Key Button_25 = "Button_25";
        public static readonly Key Button_26 = "Button_26";
        public static readonly Key Button_27 = "Button_27";
        public static readonly Key Button_28 = "Button_28";
        public static readonly Key Button_29 = "Button_29";
        public static readonly Key Button_30 = "Button_30";
        public static readonly Key Button_31 = "Button_31";
        public static readonly Key Button_32 = "Button_32";
        public static readonly Key Button_33 = "Button_33";
        public static readonly Key Button_34 = "Button_34";
        public static readonly Key Button_35 = "Button_35";
        public static readonly Key Button_36 = "Button_36";
        public static readonly Key Button_37 = "Button_37";
        public static readonly Key Button_38 = "Button_38";
        public static readonly Key Button_39 = "Button_39";
        public static readonly Key Button_40 = "Button_40";
        public static readonly Key Button_41 = "Button_41";
        public static readonly Key Button_42 = "Button_42";
        public static readonly Key Button_43 = "Button_43";
        public static readonly Key Button_44 = "Button_44";
        public static readonly Key Button_45 = "Button_45";
        public static readonly Key Button_46 = "Button_46";
        public static readonly Key Button_47 = "Button_47";
        public static readonly Key Button_48 = "Button_48";
        public static readonly Key Button_49 = "Button_49";
        public static readonly Key Button_50 = "Button_50";
        public static readonly Key Button_51 = "Button_51";
        public static readonly Key Button_52 = "Button_52";
        public static readonly Key Button_53 = "Button_53";
        public static readonly Key Button_54 = "Button_54";
        public static readonly Key Button_55 = "Button_55";
        public static readonly Key Button_56 = "Button_56";
        public static readonly Key Button_57 = "Button_57";
        public static readonly Key Button_58 = "Button_58";
        public static readonly Key Button_59 = "Button_59";
        public static readonly Key Button_60 = "Button_60";
        public static readonly Key Button_61 = "Button_61";
        public static readonly Key Button_62 = "Button_62";
        public static readonly Key Button_63 = "Button_63";
        public static readonly Key Button_64 = "Button_64";
        public static readonly Key Button_65 = "Button_65";
        public static readonly Key Button_66 = "Button_66";
        public static readonly Key Button_67 = "Button_67";
        public static readonly Key Button_68 = "Button_68";
        public static readonly Key Button_69 = "Button_69";
        public static readonly Key Button_70 = "Button_70";
        public static readonly Key Button_71 = "Button_71";
        public static readonly Key Button_72 = "Button_72";
        public static readonly Key Button_73 = "Button_73";
        public static readonly Key Button_74 = "Button_74";
        public static readonly Key Button_75 = "Button_75";
        public static readonly Key Button_76 = "Button_76";
        public static readonly Key Button_77 = "Button_77";
        public static readonly Key Button_78 = "Button_78";
        public static readonly Key Button_79 = "Button_79";
        public static readonly Key Button_80 = "Button_80";
        public static readonly Key Button_81 = "Button_81";
        public static readonly Key Button_82 = "Button_82";
        public static readonly Key Button_83 = "Button_83";
        public static readonly Key Button_84 = "Button_84";
        public static readonly Key Button_85 = "Button_85";
        public static readonly Key Button_86 = "Button_86";
        public static readonly Key Button_87 = "Button_87";
        public static readonly Key Button_88 = "Button_88";
        public static readonly Key Button_89 = "Button_89";
        public static readonly Key Button_90 = "Button_90";
        public static readonly Key Button_91 = "Button_91";
        public static readonly Key Button_92 = "Button_92";
        public static readonly Key Button_93 = "Button_93";
        public static readonly Key Button_94 = "Button_94";
        public static readonly Key Button_95 = "Button_95";
        public static readonly Key Button_96 = "Button_96";
        public static readonly Key Button_97 = "Button_97";
        public static readonly Key Button_98 = "Button_98";
        public static readonly Key Button_99 = "Button_99";
        public static readonly Key Button_100 = "Button_100";
        public static readonly Key Button_101 = "Button_101";
        public static readonly Key Button_102 = "Button_102";
        public static readonly Key Button_103 = "Button_103";
        public static readonly Key Button_104 = "Button_104";
        public static readonly Key Button_105 = "Button_105";
        public static readonly Key Button_106 = "Button_106";
        public static readonly Key Button_107 = "Button_107";
        public static readonly Key Button_108 = "Button_108";
        public static readonly Key Button_109 = "Button_109";
        public static readonly Key Button_110 = "Button_110";
        public static readonly Key Button_111 = "Button_111";
        public static readonly Key Button_112 = "Button_112";
        public static readonly Key Button_113 = "Button_113";
        public static readonly Key Button_114 = "Button_114";
        public static readonly Key Button_115 = "Button_115";
        public static readonly Key Button_116 = "Button_116";
        public static readonly Key Button_117 = "Button_117";
        public static readonly Key Button_118 = "Button_118";
        public static readonly Key Button_119 = "Button_119";
        public static readonly Key Button_120 = "Button_120";
        public static readonly Key Button_121 = "Button_121";
        public static readonly Key Button_122 = "Button_122";
        public static readonly Key Button_123 = "Button_123";
        public static readonly Key Button_124 = "Button_124";
        public static readonly Key Button_125 = "Button_125";
        public static readonly Key Button_126 = "Button_126";
        public static readonly Key Button_127 = "Button_127";
        public static readonly Key Button_128 = "Button_128";
        public static readonly Key Button_129 = "Button_129";
        public static readonly Key Button_130 = "Button_130";
        public static readonly Key Button_131 = "Button_131";
        public static readonly Key Button_132 = "Button_132";
        public static readonly Key Button_133 = "Button_133";
        public static readonly Key Button_134 = "Button_134";
        public static readonly Key Button_135 = "Button_135";
        public static readonly Key Button_136 = "Button_136";
        public static readonly Key Button_137 = "Button_137";
        public static readonly Key Button_138 = "Button_138";
        public static readonly Key Button_139 = "Button_139";
        public static readonly Key Button_140 = "Button_140";
        public static readonly Key Button_141 = "Button_141";
        public static readonly Key Button_142 = "Button_142";
        public static readonly Key Button_143 = "Button_143";
        public static readonly Key Button_144 = "Button_144";
        public static readonly Key Button_145 = "Button_145";
        public static readonly Key Button_146 = "Button_146";
        public static readonly Key Button_147 = "Button_147";
        public static readonly Key Button_148 = "Button_148";
        public static readonly Key Button_149 = "Button_149";
        public static readonly Key Button_150 = "Button_150";
        public static readonly Key Button_151 = "Button_151";
        public static readonly Key Button_152 = "Button_152";
        public static readonly Key Button_153 = "Button_153";
        public static readonly Key Button_154 = "Button_154";
        public static readonly Key Button_155 = "Button_155";
        public static readonly Key Button_156 = "Button_156";
        public static readonly Key Button_157 = "Button_157";
        public static readonly Key Button_158 = "Button_158";
        public static readonly Key Button_159 = "Button_159";
        public static readonly Key Button_160 = "Button_160";
        public static readonly Key Button_161 = "Button_161";
        public static readonly Key Button_162 = "Button_162";
        public static readonly Key Button_163 = "Button_163";
        public static readonly Key Button_164 = "Button_164";
        public static readonly Key Button_165 = "Button_165";
        public static readonly Key Button_166 = "Button_166";
        public static readonly Key Button_167 = "Button_167";
        public static readonly Key Button_168 = "Button_168";
        public static readonly Key Button_169 = "Button_169";
        public static readonly Key Button_170 = "Button_170";
        public static readonly Key Button_171 = "Button_171";
        public static readonly Key Button_172 = "Button_172";
        public static readonly Key Button_173 = "Button_173";
        public static readonly Key Button_174 = "Button_174";
        public static readonly Key Button_175 = "Button_175";
        public static readonly Key Button_176 = "Button_176";
        public static readonly Key Button_177 = "Button_177";
        public static readonly Key Button_178 = "Button_178";
        public static readonly Key Button_179 = "Button_179";
        public static readonly Key Button_180 = "Button_180";
        public static readonly Key Button_181 = "Button_181";
        public static readonly Key Button_182 = "Button_182";
        public static readonly Key Button_183 = "Button_183";
        public static readonly Key Button_184 = "Button_184";
        public static readonly Key Button_185 = "Button_185";
        public static readonly Key Button_186 = "Button_186";
        public static readonly Key Button_187 = "Button_187";
        public static readonly Key Button_188 = "Button_188";
        public static readonly Key Button_189 = "Button_189";
        public static readonly Key Button_190 = "Button_190";
        public static readonly Key Button_191 = "Button_191";
        public static readonly Key Button_192 = "Button_192";
        public static readonly Key Button_193 = "Button_193";
        public static readonly Key Button_194 = "Button_194";
        public static readonly Key Button_195 = "Button_195";
        public static readonly Key Button_196 = "Button_196";
        public static readonly Key Button_197 = "Button_197";
        public static readonly Key Button_198 = "Button_198";
        public static readonly Key Button_199 = "Button_199";
        public static readonly Key Button_200 = "Button_200";
        public static readonly Key Button_201 = "Button_201";
        public static readonly Key Button_202 = "Button_202";
        public static readonly Key Button_203 = "Button_203";
        public static readonly Key Button_204 = "Button_204";
        public static readonly Key Button_205 = "Button_205";
        public static readonly Key Button_206 = "Button_206";
        public static readonly Key Button_207 = "Button_207";
        public static readonly Key Button_208 = "Button_208";
        public static readonly Key Button_209 = "Button_209";
        public static readonly Key Button_210 = "Button_210";
        public static readonly Key Button_211 = "Button_211";
        public static readonly Key Button_212 = "Button_212";
        public static readonly Key Button_213 = "Button_213";
        public static readonly Key Button_214 = "Button_214";
        public static readonly Key Button_215 = "Button_215";
        public static readonly Key Button_216 = "Button_216";
        public static readonly Key Button_217 = "Button_217";
        public static readonly Key Button_218 = "Button_218";
        public static readonly Key Button_219 = "Button_219";
        public static readonly Key Button_220 = "Button_220";
        public static readonly Key Button_221 = "Button_221";
        public static readonly Key Button_222 = "Button_222";
        public static readonly Key Button_223 = "Button_223";
        public static readonly Key Button_224 = "Button_224";
        public static readonly Key Button_225 = "Button_225";
        public static readonly Key Button_226 = "Button_226";
        public static readonly Key Button_227 = "Button_227";
        public static readonly Key Button_228 = "Button_228";
        public static readonly Key Button_229 = "Button_229";
        public static readonly Key Button_230 = "Button_230";
        public static readonly Key Button_231 = "Button_231";
        public static readonly Key Button_232 = "Button_232";
        public static readonly Key Button_233 = "Button_233";
        public static readonly Key Button_234 = "Button_234";
        public static readonly Key Button_235 = "Button_235";
        public static readonly Key Button_236 = "Button_236";
        public static readonly Key Button_237 = "Button_237";
        public static readonly Key Button_238 = "Button_238";
        public static readonly Key Button_239 = "Button_239";
        public static readonly Key Button_240 = "Button_240";
        public static readonly Key Button_241 = "Button_241";
        public static readonly Key Button_242 = "Button_242";
        public static readonly Key Button_243 = "Button_243";
        public static readonly Key Button_244 = "Button_244";
        public static readonly Key Button_245 = "Button_245";
        public static readonly Key Button_246 = "Button_246";
        public static readonly Key Button_247 = "Button_247";
        public static readonly Key Button_248 = "Button_248";
        public static readonly Key Button_249 = "Button_249";
        public static readonly Key Button_250 = "Button_250";
        public static readonly Key Button_251 = "Button_251";
        public static readonly Key Button_252 = "Button_252";
        public static readonly Key Button_253 = "Button_253";
        public static readonly Key Button_254 = "Button_254";
        public static readonly Key Button_255 = "Button_255";

        public static readonly Key Axis_00 = "Axis_00";
        public static readonly Key Axis_01 = "Axis_01";
        public static readonly Key Axis_02 = "Axis_02";
        public static readonly Key Axis_03 = "Axis_03";
        public static readonly Key Axis_04 = "Axis_04";
        public static readonly Key Axis_05 = "Axis_05";
        public static readonly Key Axis_06 = "Axis_06";
        public static readonly Key Axis_07 = "Axis_07";
        public static readonly Key Axis_08 = "Axis_08";
        public static readonly Key Axis_09 = "Axis_09";
        public static readonly Key Axis_10 = "Axis_10";
        public static readonly Key Axis_11 = "Axis_11";
        public static readonly Key Axis_12 = "Axis_12";
        public static readonly Key Axis_13 = "Axis_13";
        public static readonly Key Axis_14 = "Axis_14";
        public static readonly Key Axis_15 = "Axis_15";
        public static readonly Key Axis_16 = "Axis_16";
        public static readonly Key Axis_17 = "Axis_17";
        public static readonly Key Axis_18 = "Axis_18";
        public static readonly Key Axis_19 = "Axis_19";
        public static readonly Key Axis_20 = "Axis_20";
        public static readonly Key Axis_21 = "Axis_21";
        public static readonly Key Axis_22 = "Axis_22";
        public static readonly Key Axis_23 = "Axis_23";
        public static readonly Key Axis_24 = "Axis_24";
        public static readonly Key Axis_25 = "Axis_25";
        public static readonly Key Axis_26 = "Axis_26";
        public static readonly Key Axis_27 = "Axis_27";
        public static readonly Key Axis_28 = "Axis_28";
        public static readonly Key Axis_29 = "Axis_29";
        public static readonly Key Axis_30 = "Axis_30";
        public static readonly Key Axis_31 = "Axis_31";

        public static readonly Key Axis_32 = "Axis_32";
        public static readonly Key Axis_33 = "Axis_33";
        public static readonly Key Axis_34 = "Axis_34";
        public static readonly Key Axis_35 = "Axis_35";
        public static readonly Key Axis_36 = "Axis_36";
        public static readonly Key Axis_37 = "Axis_37";
        public static readonly Key Axis_38 = "Axis_38";
        public static readonly Key Axis_39 = "Axis_39";
        public static readonly Key Axis_40 = "Axis_40";
        public static readonly Key Axis_41 = "Axis_41";
        public static readonly Key Axis_42 = "Axis_42";
        public static readonly Key Axis_43 = "Axis_43";
        public static readonly Key Axis_44 = "Axis_44";
        public static readonly Key Axis_45 = "Axis_45";
        public static readonly Key Axis_46 = "Axis_46";
        public static readonly Key Axis_47 = "Axis_47";
        public static readonly Key Axis_48 = "Axis_48";
        public static readonly Key Axis_49 = "Axis_49";
        public static readonly Key Axis_50 = "Axis_50";
        public static readonly Key Axis_51 = "Axis_51";
        public static readonly Key Axis_52 = "Axis_52";
        public static readonly Key Axis_53 = "Axis_53";
        public static readonly Key Axis_54 = "Axis_54";
        public static readonly Key Axis_55 = "Axis_55";
        public static readonly Key Axis_56 = "Axis_56";
        public static readonly Key Axis_57 = "Axis_57";
        public static readonly Key Axis_58 = "Axis_58";
        public static readonly Key Axis_59 = "Axis_59";
        public static readonly Key Axis_60 = "Axis_60";
        public static readonly Key Axis_61 = "Axis_61";
        public static readonly Key Axis_62 = "Axis_62";
        public static readonly Key Axis_63 = "Axis_63";
        public static readonly Key Axis_64 = "Axis_64";
        public static readonly Key Axis_65 = "Axis_65";
        public static readonly Key Axis_66 = "Axis_66";
        public static readonly Key Axis_67 = "Axis_67";
        public static readonly Key Axis_68 = "Axis_68";
        public static readonly Key Axis_69 = "Axis_69";
        public static readonly Key Axis_70 = "Axis_70";
        public static readonly Key Axis_71 = "Axis_71";
        public static readonly Key Axis_72 = "Axis_72";
        public static readonly Key Axis_73 = "Axis_73";
        public static readonly Key Axis_74 = "Axis_74";
        public static readonly Key Axis_75 = "Axis_75";
        public static readonly Key Axis_76 = "Axis_76";
        public static readonly Key Axis_77 = "Axis_77";
        public static readonly Key Axis_78 = "Axis_78";
        public static readonly Key Axis_79 = "Axis_79";
        public static readonly Key Axis_80 = "Axis_80";
        public static readonly Key Axis_81 = "Axis_81";
        public static readonly Key Axis_82 = "Axis_82";
        public static readonly Key Axis_83 = "Axis_83";
        public static readonly Key Axis_84 = "Axis_84";
        public static readonly Key Axis_85 = "Axis_85";
        public static readonly Key Axis_86 = "Axis_86";
        public static readonly Key Axis_87 = "Axis_87";
        public static readonly Key Axis_88 = "Axis_88";
        public static readonly Key Axis_89 = "Axis_89";
        public static readonly Key Axis_90 = "Axis_90";
        public static readonly Key Axis_91 = "Axis_91";
        public static readonly Key Axis_92 = "Axis_92";
        public static readonly Key Axis_93 = "Axis_93";
        public static readonly Key Axis_94 = "Axis_94";
        public static readonly Key Axis_95 = "Axis_95";
        public static readonly Key Axis_96 = "Axis_96";
        public static readonly Key Axis_97 = "Axis_97";
        public static readonly Key Axis_98 = "Axis_98";
        public static readonly Key Axis_99 = "Axis_99";
        public static readonly Key Axis_100 = "Axis_100";
        public static readonly Key Axis_101 = "Axis_101";
        public static readonly Key Axis_102 = "Axis_102";
        public static readonly Key Axis_103 = "Axis_103";
        public static readonly Key Axis_104 = "Axis_104";
        public static readonly Key Axis_105 = "Axis_105";
        public static readonly Key Axis_106 = "Axis_106";
        public static readonly Key Axis_107 = "Axis_107";
        public static readonly Key Axis_108 = "Axis_108";
        public static readonly Key Axis_109 = "Axis_109";
        public static readonly Key Axis_110 = "Axis_110";
        public static readonly Key Axis_111 = "Axis_111";
        public static readonly Key Axis_112 = "Axis_112";
        public static readonly Key Axis_113 = "Axis_113";
        public static readonly Key Axis_114 = "Axis_114";
        public static readonly Key Axis_115 = "Axis_115";
        public static readonly Key Axis_116 = "Axis_116";
        public static readonly Key Axis_117 = "Axis_117";
        public static readonly Key Axis_118 = "Axis_118";
        public static readonly Key Axis_119 = "Axis_119";
        public static readonly Key Axis_120 = "Axis_120";
        public static readonly Key Axis_121 = "Axis_121";
        public static readonly Key Axis_122 = "Axis_122";
        public static readonly Key Axis_123 = "Axis_123";
        public static readonly Key Axis_124 = "Axis_124";
        public static readonly Key Axis_125 = "Axis_125";
        public static readonly Key Axis_126 = "Axis_126";
        public static readonly Key Axis_127 = "Axis_127";
        public static readonly Key Axis_128 = "Axis_128";
        public static readonly Key Axis_129 = "Axis_129";
        public static readonly Key Axis_130 = "Axis_130";
        public static readonly Key Axis_131 = "Axis_131";
        public static readonly Key Axis_132 = "Axis_132";
        public static readonly Key Axis_133 = "Axis_133";
        public static readonly Key Axis_134 = "Axis_134";
        public static readonly Key Axis_135 = "Axis_135";
        public static readonly Key Axis_136 = "Axis_136";
        public static readonly Key Axis_137 = "Axis_137";
        public static readonly Key Axis_138 = "Axis_138";
        public static readonly Key Axis_139 = "Axis_139";
        public static readonly Key Axis_140 = "Axis_140";
        public static readonly Key Axis_141 = "Axis_141";
        public static readonly Key Axis_142 = "Axis_142";
        public static readonly Key Axis_143 = "Axis_143";
        public static readonly Key Axis_144 = "Axis_144";
        public static readonly Key Axis_145 = "Axis_145";
        public static readonly Key Axis_146 = "Axis_146";
        public static readonly Key Axis_147 = "Axis_147";
        public static readonly Key Axis_148 = "Axis_148";
        public static readonly Key Axis_149 = "Axis_149";
        public static readonly Key Axis_150 = "Axis_150";
        public static readonly Key Axis_151 = "Axis_151";
        public static readonly Key Axis_152 = "Axis_152";
        public static readonly Key Axis_153 = "Axis_153";
        public static readonly Key Axis_154 = "Axis_154";
        public static readonly Key Axis_155 = "Axis_155";
        public static readonly Key Axis_156 = "Axis_156";
        public static readonly Key Axis_157 = "Axis_157";
        public static readonly Key Axis_158 = "Axis_158";
        public static readonly Key Axis_159 = "Axis_159";
        public static readonly Key Axis_160 = "Axis_160";
        public static readonly Key Axis_161 = "Axis_161";
        public static readonly Key Axis_162 = "Axis_162";
        public static readonly Key Axis_163 = "Axis_163";
        public static readonly Key Axis_164 = "Axis_164";
        public static readonly Key Axis_165 = "Axis_165";
        public static readonly Key Axis_166 = "Axis_166";
        public static readonly Key Axis_167 = "Axis_167";
        public static readonly Key Axis_168 = "Axis_168";
        public static readonly Key Axis_169 = "Axis_169";
        public static readonly Key Axis_170 = "Axis_170";
        public static readonly Key Axis_171 = "Axis_171";
        public static readonly Key Axis_172 = "Axis_172";
        public static readonly Key Axis_173 = "Axis_173";
        public static readonly Key Axis_174 = "Axis_174";
        public static readonly Key Axis_175 = "Axis_175";
        public static readonly Key Axis_176 = "Axis_176";
        public static readonly Key Axis_177 = "Axis_177";
        public static readonly Key Axis_178 = "Axis_178";
        public static readonly Key Axis_179 = "Axis_179";
        public static readonly Key Axis_180 = "Axis_180";
        public static readonly Key Axis_181 = "Axis_181";
        public static readonly Key Axis_182 = "Axis_182";
        public static readonly Key Axis_183 = "Axis_183";
        public static readonly Key Axis_184 = "Axis_184";
        public static readonly Key Axis_185 = "Axis_185";
        public static readonly Key Axis_186 = "Axis_186";
        public static readonly Key Axis_187 = "Axis_187";
        public static readonly Key Axis_188 = "Axis_188";
        public static readonly Key Axis_189 = "Axis_189";
        public static readonly Key Axis_190 = "Axis_190";
        public static readonly Key Axis_191 = "Axis_191";
        public static readonly Key Axis_192 = "Axis_192";
        public static readonly Key Axis_193 = "Axis_193";
        public static readonly Key Axis_194 = "Axis_194";
        public static readonly Key Axis_195 = "Axis_195";
        public static readonly Key Axis_196 = "Axis_196";
        public static readonly Key Axis_197 = "Axis_197";
        public static readonly Key Axis_198 = "Axis_198";
        public static readonly Key Axis_199 = "Axis_199";
        public static readonly Key Axis_200 = "Axis_200";
        public static readonly Key Axis_201 = "Axis_201";
        public static readonly Key Axis_202 = "Axis_202";
        public static readonly Key Axis_203 = "Axis_203";
        public static readonly Key Axis_204 = "Axis_204";
        public static readonly Key Axis_205 = "Axis_205";
        public static readonly Key Axis_206 = "Axis_206";
        public static readonly Key Axis_207 = "Axis_207";
        public static readonly Key Axis_208 = "Axis_208";
        public static readonly Key Axis_209 = "Axis_209";
        public static readonly Key Axis_210 = "Axis_210";
        public static readonly Key Axis_211 = "Axis_211";
        public static readonly Key Axis_212 = "Axis_212";
        public static readonly Key Axis_213 = "Axis_213";
        public static readonly Key Axis_214 = "Axis_214";
        public static readonly Key Axis_215 = "Axis_215";
        public static readonly Key Axis_216 = "Axis_216";
        public static readonly Key Axis_217 = "Axis_217";
        public static readonly Key Axis_218 = "Axis_218";
        public static readonly Key Axis_219 = "Axis_219";
        public static readonly Key Axis_220 = "Axis_220";
        public static readonly Key Axis_221 = "Axis_221";
        public static readonly Key Axis_222 = "Axis_222";
        public static readonly Key Axis_223 = "Axis_223";
        public static readonly Key Axis_224 = "Axis_224";
        public static readonly Key Axis_225 = "Axis_225";
        public static readonly Key Axis_226 = "Axis_226";
        public static readonly Key Axis_227 = "Axis_227";
        public static readonly Key Axis_228 = "Axis_228";
        public static readonly Key Axis_229 = "Axis_229";
        public static readonly Key Axis_230 = "Axis_230";
        public static readonly Key Axis_231 = "Axis_231";
        public static readonly Key Axis_232 = "Axis_232";
        public static readonly Key Axis_233 = "Axis_233";
        public static readonly Key Axis_234 = "Axis_234";
        public static readonly Key Axis_235 = "Axis_235";
        public static readonly Key Axis_236 = "Axis_236";
        public static readonly Key Axis_237 = "Axis_237";
        public static readonly Key Axis_238 = "Axis_238";
        public static readonly Key Axis_239 = "Axis_239";
        public static readonly Key Axis_240 = "Axis_240";
        public static readonly Key Axis_241 = "Axis_241";
        public static readonly Key Axis_242 = "Axis_242";
        public static readonly Key Axis_243 = "Axis_243";
        public static readonly Key Axis_244 = "Axis_244";
        public static readonly Key Axis_245 = "Axis_245";
        public static readonly Key Axis_246 = "Axis_246";
        public static readonly Key Axis_247 = "Axis_247";
        public static readonly Key Axis_248 = "Axis_248";
        public static readonly Key Axis_249 = "Axis_249";
        public static readonly Key Axis_250 = "Axis_250";
        public static readonly Key Axis_251 = "Axis_251";
        public static readonly Key Axis_252 = "Axis_252";
        public static readonly Key Axis_253 = "Axis_253";
        public static readonly Key Axis_254 = "Axis_254";
        public static readonly Key Axis_255 = "Axis_255";

        public static readonly Key OAxis_00 = "OAxis_00";
        public static readonly Key OAxis_01 = "OAxis_01";
        public static readonly Key OAxis_02 = "OAxis_02";
        public static readonly Key OAxis_03 = "OAxis_03";
        public static readonly Key OAxis_04 = "OAxis_04";
        public static readonly Key OAxis_05 = "OAxis_05";
        public static readonly Key OAxis_06 = "OAxis_06";
        public static readonly Key OAxis_07 = "OAxis_07";
        public static readonly Key OAxis_08 = "OAxis_08";
        public static readonly Key OAxis_09 = "OAxis_09";
        public static readonly Key OAxis_10 = "OAxis_10";
        public static readonly Key OAxis_11 = "OAxis_11";
        public static readonly Key OAxis_12 = "OAxis_12";
        public static readonly Key OAxis_13 = "OAxis_13";
        public static readonly Key OAxis_14 = "OAxis_14";
        public static readonly Key OAxis_15 = "OAxis_15";
        public static readonly Key OAxis_16 = "OAxis_16";
        public static readonly Key OAxis_17 = "OAxis_17";
        public static readonly Key OAxis_18 = "OAxis_18";
        public static readonly Key OAxis_19 = "OAxis_19";
        public static readonly Key OAxis_20 = "OAxis_20";
        public static readonly Key OAxis_21 = "OAxis_21";
        public static readonly Key OAxis_22 = "OAxis_22";
        public static readonly Key OAxis_23 = "OAxis_23";
        public static readonly Key OAxis_24 = "OAxis_24";
        public static readonly Key OAxis_25 = "OAxis_25";
        public static readonly Key OAxis_26 = "OAxis_26";
        public static readonly Key OAxis_27 = "OAxis_27";
        public static readonly Key OAxis_28 = "OAxis_28";
        public static readonly Key OAxis_29 = "OAxis_29";
        public static readonly Key OAxis_30 = "OAxis_30";
        public static readonly Key OAxis_31 = "OAxis_31";
        public static readonly Key OAxis_32 = "OAxis_32";
        public static readonly Key OAxis_33 = "OAxis_33";
        public static readonly Key OAxis_34 = "OAxis_34";
        public static readonly Key OAxis_35 = "OAxis_35";
        public static readonly Key OAxis_36 = "OAxis_36";
        public static readonly Key OAxis_37 = "OAxis_37";
        public static readonly Key OAxis_38 = "OAxis_38";
        public static readonly Key OAxis_39 = "OAxis_39";
        public static readonly Key OAxis_40 = "OAxis_40";
        public static readonly Key OAxis_41 = "OAxis_41";
        public static readonly Key OAxis_42 = "OAxis_42";
        public static readonly Key OAxis_43 = "OAxis_43";
        public static readonly Key OAxis_44 = "OAxis_44";
        public static readonly Key OAxis_45 = "OAxis_45";
        public static readonly Key OAxis_46 = "OAxis_46";
        public static readonly Key OAxis_47 = "OAxis_47";
        public static readonly Key OAxis_48 = "OAxis_48";
        public static readonly Key OAxis_49 = "OAxis_49";
        public static readonly Key OAxis_50 = "OAxis_50";
        public static readonly Key OAxis_51 = "OAxis_51";
        public static readonly Key OAxis_52 = "OAxis_52";
        public static readonly Key OAxis_53 = "OAxis_53";
        public static readonly Key OAxis_54 = "OAxis_54";
        public static readonly Key OAxis_55 = "OAxis_55";
        public static readonly Key OAxis_56 = "OAxis_56";
        public static readonly Key OAxis_57 = "OAxis_57";
        public static readonly Key OAxis_58 = "OAxis_58";
        public static readonly Key OAxis_59 = "OAxis_59";
        public static readonly Key OAxis_60 = "OAxis_60";
        public static readonly Key OAxis_61 = "OAxis_61";
        public static readonly Key OAxis_62 = "OAxis_62";
        public static readonly Key OAxis_63 = "OAxis_63";
        public static readonly Key OAxis_64 = "OAxis_64";
        public static readonly Key OAxis_65 = "OAxis_65";
        public static readonly Key OAxis_66 = "OAxis_66";
        public static readonly Key OAxis_67 = "OAxis_67";
        public static readonly Key OAxis_68 = "OAxis_68";
        public static readonly Key OAxis_69 = "OAxis_69";
        public static readonly Key OAxis_70 = "OAxis_70";
        public static readonly Key OAxis_71 = "OAxis_71";
        public static readonly Key OAxis_72 = "OAxis_72";
        public static readonly Key OAxis_73 = "OAxis_73";
        public static readonly Key OAxis_74 = "OAxis_74";
        public static readonly Key OAxis_75 = "OAxis_75";
        public static readonly Key OAxis_76 = "OAxis_76";
        public static readonly Key OAxis_77 = "OAxis_77";
        public static readonly Key OAxis_78 = "OAxis_78";
        public static readonly Key OAxis_79 = "OAxis_79";
        public static readonly Key OAxis_80 = "OAxis_80";
        public static readonly Key OAxis_81 = "OAxis_81";
        public static readonly Key OAxis_82 = "OAxis_82";
        public static readonly Key OAxis_83 = "OAxis_83";
        public static readonly Key OAxis_84 = "OAxis_84";
        public static readonly Key OAxis_85 = "OAxis_85";
        public static readonly Key OAxis_86 = "OAxis_86";
        public static readonly Key OAxis_87 = "OAxis_87";
        public static readonly Key OAxis_88 = "OAxis_88";
        public static readonly Key OAxis_89 = "OAxis_89";
        public static readonly Key OAxis_90 = "OAxis_90";
        public static readonly Key OAxis_91 = "OAxis_91";
        public static readonly Key OAxis_92 = "OAxis_92";
        public static readonly Key OAxis_93 = "OAxis_93";
        public static readonly Key OAxis_94 = "OAxis_94";
        public static readonly Key OAxis_95 = "OAxis_95";
        public static readonly Key OAxis_96 = "OAxis_96";
        public static readonly Key OAxis_97 = "OAxis_97";
        public static readonly Key OAxis_98 = "OAxis_98";
        public static readonly Key OAxis_99 = "OAxis_99";
        public static readonly Key OAxis_100 = "OAxis_100";
        public static readonly Key OAxis_101 = "OAxis_101";
        public static readonly Key OAxis_102 = "OAxis_102";
        public static readonly Key OAxis_103 = "OAxis_103";
        public static readonly Key OAxis_104 = "OAxis_104";
        public static readonly Key OAxis_105 = "OAxis_105";
        public static readonly Key OAxis_106 = "OAxis_106";
        public static readonly Key OAxis_107 = "OAxis_107";
        public static readonly Key OAxis_108 = "OAxis_108";
        public static readonly Key OAxis_109 = "OAxis_109";
        public static readonly Key OAxis_110 = "OAxis_110";
        public static readonly Key OAxis_111 = "OAxis_111";
        public static readonly Key OAxis_112 = "OAxis_112";
        public static readonly Key OAxis_113 = "OAxis_113";
        public static readonly Key OAxis_114 = "OAxis_114";
        public static readonly Key OAxis_115 = "OAxis_115";
        public static readonly Key OAxis_116 = "OAxis_116";
        public static readonly Key OAxis_117 = "OAxis_117";
        public static readonly Key OAxis_118 = "OAxis_118";
        public static readonly Key OAxis_119 = "OAxis_119";
        public static readonly Key OAxis_120 = "OAxis_120";
        public static readonly Key OAxis_121 = "OAxis_121";
        public static readonly Key OAxis_122 = "OAxis_122";
        public static readonly Key OAxis_123 = "OAxis_123";
        public static readonly Key OAxis_124 = "OAxis_124";
        public static readonly Key OAxis_125 = "OAxis_125";
        public static readonly Key OAxis_126 = "OAxis_126";
        public static readonly Key OAxis_127 = "OAxis_127";
        public static readonly Key OAxis_128 = "OAxis_128";
        public static readonly Key OAxis_129 = "OAxis_129";
        public static readonly Key OAxis_130 = "OAxis_130";
        public static readonly Key OAxis_131 = "OAxis_131";
        public static readonly Key OAxis_132 = "OAxis_132";
        public static readonly Key OAxis_133 = "OAxis_133";
        public static readonly Key OAxis_134 = "OAxis_134";
        public static readonly Key OAxis_135 = "OAxis_135";
        public static readonly Key OAxis_136 = "OAxis_136";
        public static readonly Key OAxis_137 = "OAxis_137";
        public static readonly Key OAxis_138 = "OAxis_138";
        public static readonly Key OAxis_139 = "OAxis_139";
        public static readonly Key OAxis_140 = "OAxis_140";
        public static readonly Key OAxis_141 = "OAxis_141";
        public static readonly Key OAxis_142 = "OAxis_142";
        public static readonly Key OAxis_143 = "OAxis_143";
        public static readonly Key OAxis_144 = "OAxis_144";
        public static readonly Key OAxis_145 = "OAxis_145";
        public static readonly Key OAxis_146 = "OAxis_146";
        public static readonly Key OAxis_147 = "OAxis_147";
        public static readonly Key OAxis_148 = "OAxis_148";
        public static readonly Key OAxis_149 = "OAxis_149";
        public static readonly Key OAxis_150 = "OAxis_150";
        public static readonly Key OAxis_151 = "OAxis_151";
        public static readonly Key OAxis_152 = "OAxis_152";
        public static readonly Key OAxis_153 = "OAxis_153";
        public static readonly Key OAxis_154 = "OAxis_154";
        public static readonly Key OAxis_155 = "OAxis_155";
        public static readonly Key OAxis_156 = "OAxis_156";
        public static readonly Key OAxis_157 = "OAxis_157";
        public static readonly Key OAxis_158 = "OAxis_158";
        public static readonly Key OAxis_159 = "OAxis_159";
        public static readonly Key OAxis_160 = "OAxis_160";
        public static readonly Key OAxis_161 = "OAxis_161";
        public static readonly Key OAxis_162 = "OAxis_162";
        public static readonly Key OAxis_163 = "OAxis_163";
        public static readonly Key OAxis_164 = "OAxis_164";
        public static readonly Key OAxis_165 = "OAxis_165";
        public static readonly Key OAxis_166 = "OAxis_166";
        public static readonly Key OAxis_167 = "OAxis_167";
        public static readonly Key OAxis_168 = "OAxis_168";
        public static readonly Key OAxis_169 = "OAxis_169";
        public static readonly Key OAxis_170 = "OAxis_170";
        public static readonly Key OAxis_171 = "OAxis_171";
        public static readonly Key OAxis_172 = "OAxis_172";
        public static readonly Key OAxis_173 = "OAxis_173";
        public static readonly Key OAxis_174 = "OAxis_174";
        public static readonly Key OAxis_175 = "OAxis_175";
        public static readonly Key OAxis_176 = "OAxis_176";
        public static readonly Key OAxis_177 = "OAxis_177";
        public static readonly Key OAxis_178 = "OAxis_178";
        public static readonly Key OAxis_179 = "OAxis_179";
        public static readonly Key OAxis_180 = "OAxis_180";
        public static readonly Key OAxis_181 = "OAxis_181";
        public static readonly Key OAxis_182 = "OAxis_182";
        public static readonly Key OAxis_183 = "OAxis_183";
        public static readonly Key OAxis_184 = "OAxis_184";
        public static readonly Key OAxis_185 = "OAxis_185";
        public static readonly Key OAxis_186 = "OAxis_186";
        public static readonly Key OAxis_187 = "OAxis_187";
        public static readonly Key OAxis_188 = "OAxis_188";
        public static readonly Key OAxis_189 = "OAxis_189";
        public static readonly Key OAxis_190 = "OAxis_190";
        public static readonly Key OAxis_191 = "OAxis_191";
        public static readonly Key OAxis_192 = "OAxis_192";
        public static readonly Key OAxis_193 = "OAxis_193";
        public static readonly Key OAxis_194 = "OAxis_194";
        public static readonly Key OAxis_195 = "OAxis_195";
        public static readonly Key OAxis_196 = "OAxis_196";
        public static readonly Key OAxis_197 = "OAxis_197";
        public static readonly Key OAxis_198 = "OAxis_198";
        public static readonly Key OAxis_199 = "OAxis_199";
        public static readonly Key OAxis_200 = "OAxis_200";
        public static readonly Key OAxis_201 = "OAxis_201";
        public static readonly Key OAxis_202 = "OAxis_202";
        public static readonly Key OAxis_203 = "OAxis_203";
        public static readonly Key OAxis_204 = "OAxis_204";
        public static readonly Key OAxis_205 = "OAxis_205";
        public static readonly Key OAxis_206 = "OAxis_206";
        public static readonly Key OAxis_207 = "OAxis_207";
        public static readonly Key OAxis_208 = "OAxis_208";
        public static readonly Key OAxis_209 = "OAxis_209";
        public static readonly Key OAxis_210 = "OAxis_210";
        public static readonly Key OAxis_211 = "OAxis_211";
        public static readonly Key OAxis_212 = "OAxis_212";
        public static readonly Key OAxis_213 = "OAxis_213";
        public static readonly Key OAxis_214 = "OAxis_214";
        public static readonly Key OAxis_215 = "OAxis_215";
        public static readonly Key OAxis_216 = "OAxis_216";
        public static readonly Key OAxis_217 = "OAxis_217";
        public static readonly Key OAxis_218 = "OAxis_218";
        public static readonly Key OAxis_219 = "OAxis_219";
        public static readonly Key OAxis_220 = "OAxis_220";
        public static readonly Key OAxis_221 = "OAxis_221";
        public static readonly Key OAxis_222 = "OAxis_222";
        public static readonly Key OAxis_223 = "OAxis_223";
        public static readonly Key OAxis_224 = "OAxis_224";
        public static readonly Key OAxis_225 = "OAxis_225";
        public static readonly Key OAxis_226 = "OAxis_226";
        public static readonly Key OAxis_227 = "OAxis_227";
        public static readonly Key OAxis_228 = "OAxis_228";
        public static readonly Key OAxis_229 = "OAxis_229";
        public static readonly Key OAxis_230 = "OAxis_230";
        public static readonly Key OAxis_231 = "OAxis_231";
        public static readonly Key OAxis_232 = "OAxis_232";
        public static readonly Key OAxis_233 = "OAxis_233";
        public static readonly Key OAxis_234 = "OAxis_234";
        public static readonly Key OAxis_235 = "OAxis_235";
        public static readonly Key OAxis_236 = "OAxis_236";
        public static readonly Key OAxis_237 = "OAxis_237";
        public static readonly Key OAxis_238 = "OAxis_238";
        public static readonly Key OAxis_239 = "OAxis_239";
        public static readonly Key OAxis_240 = "OAxis_240";
        public static readonly Key OAxis_241 = "OAxis_241";
        public static readonly Key OAxis_242 = "OAxis_242";
        public static readonly Key OAxis_243 = "OAxis_243";
        public static readonly Key OAxis_244 = "OAxis_244";
        public static readonly Key OAxis_245 = "OAxis_245";
        public static readonly Key OAxis_246 = "OAxis_246";
        public static readonly Key OAxis_247 = "OAxis_247";
        public static readonly Key OAxis_248 = "OAxis_248";
        public static readonly Key OAxis_249 = "OAxis_249";
        public static readonly Key OAxis_250 = "OAxis_250";
        public static readonly Key OAxis_251 = "OAxis_251";
        public static readonly Key OAxis_252 = "OAxis_252";
        public static readonly Key OAxis_253 = "OAxis_253";
        public static readonly Key OAxis_254 = "OAxis_254";
        public static readonly Key OAxis_255 = "OAxis_255";

        /** Joystick axes */
        /** Joystick axes */
        public static readonly Key JS_X = "JS_X"; /* x-axis position              */
        public static readonly Key JS_Y = "JS_Y"; /* y-axis position              */
        public static readonly Key JS_Z = "JS_Z"; /* z-axis position              */
        public static readonly Key JS_Rx = "JS_Rx"; /* x-axis rotation              */
        public static readonly Key JS_Ry = "JS_Ry"; /* y-axis rotation              */
        public static readonly Key JS_Rz = "JS_Rz"; /* z-axis rotation              */
        public static readonly Key JS_VX = "JS_VX"; /* x-axis velocity              */
        public static readonly Key JS_VY = "JS_VY"; /* y-axis velocity              */
        public static readonly Key JS_VZ = "JS_VZ"; /* z-axis velocity              */
        public static readonly Key JS_VRx = "JS_VRx"; /* x-axis angular velocity      */
        public static readonly Key JS_VRy = "JS_VRy"; /* y-axis angular velocity      */
        public static readonly Key JS_VRz = "JS_VRz"; /* z-axis angular velocity      */
        public static readonly Key JS_AX = "JS_AX"; /* x-axis acceleration          */
        public static readonly Key JS_AY = "JS_AY"; /* y-axis acceleration          */
        public static readonly Key JS_AZ = "JS_AZ"; /* z-axis acceleration          */
        public static readonly Key JS_ARx = "JS_ARx"; /* x-axis angular acceleration  */
        public static readonly Key JS_ARy = "JS_ARy"; /* y-axis angular acceleration  */
        public static readonly Key JS_ARz = "JS_ARz"; /* z-axis angular acceleration  */
        public static readonly Key JS_FX = "JS_FX"; /* x-axis force                 */
        public static readonly Key JS_FY = "JS_FY"; /* y-axis force                 */
        public static readonly Key JS_FZ = "JS_FZ"; /* z-axis force                 */
        public static readonly Key JS_FRx = "JS_FRx"; /* x-axis torque                */
        public static readonly Key JS_FRy = "JS_FRy"; /* y-axis torque                */
        public static readonly Key JS_FRz = "JS_FRz"; /* z-axis torque                */

        public static readonly Key JS_Slider_00 = "JS_Slider_00"; /* extra axes positions         */
        public static readonly Key JS_Slider_01 = "JS_Slider_01"; /* extra axes positions         */

        public static readonly Key JS_VSlider_00 = "JS_VSlider_00"; /* extra axes velocities        */
        public static readonly Key JS_VSlider_01 = "JS_VSlider_01"; /* extra axes velocities        */

        public static readonly Key JS_ASlider_00 = "JS_ASlider_00"; /* extra axes accelerations     */
        public static readonly Key JS_ASlider_01 = "JS_ASlider_01"; /* extra axes accelerations     */

        public static readonly Key JS_FSlider_00 = "JS_FSlider_00"; /* extra axes forces            */
        public static readonly Key JS_FSlider_01 = "JS_FSlider_01"; /* extra axes forces            */

        public static readonly Key JS_POV_00 = "JS_POV_00"; /* POV directions               */
        public static readonly Key JS_POV_01 = "JS_POV_01"; /* POV directions               */
        public static readonly Key JS_POV_02 = "JS_POV_02"; /* POV directions               */
        public static readonly Key JS_POV_03 = "JS_POV_03"; /* POV directions               */
    };
}
